"""Initial migration: Create user table

Revision ID: b916a4842043
Revises: 
Create Date: 2025-12-20 10:37:04.450430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b916a4842043'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('street_number', sa.String(length=10), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.drop_table('spt_fallback_dev')
    op.drop_table('spt_monitor')
    op.drop_table('spt_fallback_usg')
    op.drop_table('MSreplication_options')
    op.drop_table('spt_fallback_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spt_fallback_db',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_dbid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('dbid', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.SMALLINT(), autoincrement=False, nullable=False)
    )
    op.create_table('MSreplication_options',
    sa.Column('optname', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('value', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('major_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minor_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revision', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('install_failures', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_usg',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_vstart', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dbid', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('segmap', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lstart', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sizepg', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vstart', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_monitor',
    sa.Column('lastrun', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('cpu_busy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('io_busy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_received', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_sent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connections', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_errors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_read', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_write', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_errors', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_dev',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_low', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('xfallback_drive', sa.CHAR(length=2, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('low', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('high', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('phyname', sa.VARCHAR(length=127, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False)
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
